"""initial schema

Revision ID: a73aab154d57
Revises: 
Create Date: 2026-04-15 11:17:46.331156
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a73aab154d57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_number', sa.String(length=100), nullable=False),
    sa.Column('gat_number', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=False),
    sa.Column('taluka', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('area_sqft', sa.Float(), nullable=False),
    sa.Column('current_owner', sa.String(length=255), nullable=False),
    sa.Column('owner_contact', sa.String(length=20), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_current_owner'), 'properties', ['current_owner'], unique=False)
    op.create_index(op.f('ix_properties_district'), 'properties', ['district'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_survey_number'), 'properties', ['survey_number'], unique=False)
    op.create_index(op.f('ix_properties_taluka'), 'properties', ['taluka'], unique=False)
    op.create_index(op.f('ix_properties_village'), 'properties', ['village'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('deeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('deed_type', sa.String(length=50), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('registration_number', sa.String(length=150), nullable=False),
    sa.Column('parties', sa.JSON(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_deeds_id'), 'deeds', ['id'], unique=False)
    op.create_index(op.f('ix_deeds_property_id'), 'deeds', ['property_id'], unique=False)
    op.create_table('encumbrances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('enc_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encumbrances_id'), 'encumbrances', ['id'], unique=False)
    op.create_index(op.f('ix_encumbrances_property_id'), 'encumbrances', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encumbrances_property_id'), table_name='encumbrances')
    op.drop_index(op.f('ix_encumbrances_id'), table_name='encumbrances')
    op.drop_table('encumbrances')
    op.drop_index(op.f('ix_deeds_property_id'), table_name='deeds')
    op.drop_index(op.f('ix_deeds_id'), table_name='deeds')
    op.drop_table('deeds')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_properties_village'), table_name='properties')
    op.drop_index(op.f('ix_properties_taluka'), table_name='properties')
    op.drop_index(op.f('ix_properties_survey_number'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_district'), table_name='properties')
    op.drop_index(op.f('ix_properties_current_owner'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
